### ISSUE TITLE
Allow single file modules as `--source` parameters

### ISSUE THREAD

**Issue by Calder-Ty** [Calder-Ty/realreq#2]
# What do you want?

It would be nice to have `--source` accept a single python file, so that a
single module package can use realreq without having to be inside a subdirectory

**Comment by matt-oehler-dev** [comment]
Is this issue still open/are you looking for help on it? I'd love to look into this.

**Comment by Calder-Ty** [comment]
I had to check and yes this is still an issue. I would love to accept a PR for it. 

To test out the differences you can see how realreq works correcty with our own testing module. When your run: `realreq -s tests -d` versus `realreq -s tests/test_realreq.py -d`. I would expect them both to generate the same results.

**Comment by Calder-Ty** [comment]
woops didn't mean to close

**Comment by Calder-Ty** [comment]
Also. The Testing module can be fairly difficult to parse as I haven't put a lot of effort into making it nice. Let me know if you need help around testing.

**Comment by Calder-Ty** [comment]
Completed, and merged to v0.7.1
